{
  "altLangUrl": {
    "en": "https://design.canada.ca",
    "fr": "https://canada-ca.github.io/systeme-conception"
  },
  "analytics": {
    "provider": {
      "google": {
        "tracking_id": "GTM-KMVB8C2"
      },
      "adobe": {
        "tracking_id": "be5dfd287373/0127575cd23a/launch-f7c3e6060667",
        "service": "ESDC-EDSC",
        "gcaaterms": "ESDC-EDSC_CanadacaDesign-ConceptionCanadaca"
      }
    }
  },
  "author": {
    "fr": "Emploi et Développement social Canada"
  },
  "baseurl": "",
  "exclude": [
    ".editorconfig",
    ".jekyll-cache",
    ".gitignore",
    ".github",
    "*.gpg",
    "*.py",
    "*.tmp",
    "CNAME",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "gcweb-jekyll.gemspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE*",
    "log_*",
    "netlify.toml",
    "node_modules",
    "package*.json",
    "README.md",
    "screenshot.*",
    "SECURITY.md",
    "vendor"
  ],
  "include": [
    "_redirects"
  ],
  "institutionopt": "edsc",
  "global": {
    "contextualFooter": {
      "title": {
        "fr": "Bureau de l’expérience Canada.ca (BEC)"
      },
      "links": {
        "fr": [{
          "url": "https://blogue.canada.ca/contactez-nous",
          "text": "Contactez-nous"
        }]
      }
    },
    "feedbackPath": {
      "fr": "https://www.canada.ca/etc/designs/canada/wet-boew/assets/feedback/page-feedback-fr.html"
    },
    "lang": "fr",
    "sitemenuPath": {
      "fr": "https://www.canada.ca/content/dam/canada/sitemenu/sitemenu-v2-fr.html"
    }
  },
  "language": {
    "en": "English",
    "fr": "Français"
  },
  "plugins": [
    "jekyll-remote-theme"
  ],
  "remote_theme": "wet-boew/gcweb-jekyll",
  "themeopt": "Policies",
  "title": "Conception de Canada.ca",
  "url": "https://canada-ca.github.io/systeme-conception",
  "urldesign": "https://design.canada.ca",
  "urlcanadaca": "https://www.canada.ca",
  "urlblogue": "https://blogue.canada.ca",
  "emails": {
    "dto": "cds.dto-btn.snc@servicecanada.gc.ca",
    "atip": "ATIP.AIPRP@tbs-sct.gc.ca"
  },
  "webmaster_verifications": {
    "google": "Nt_CftRIypA9xVS7Znb2VkrsYbtIDuFWHryxSAC6OwM",
    "yandex": "4dda5b1b6e392d83"
  },
  "defaults": [{
      "scope": {
        "path": "**/*.md"
      },
      "values": {
        "css": [
          "https://use.fontawesome.com/releases/v5.15.4/css/all.css",
          "/css/custom.css"
        ],
        "feedback": true,
        "feedbackData": {
          "theme": "AboutGov"
        },
        "lang": "fr",
        "layout": "default",
        "pageclass": "cnt-wdth-lmtd",
        "script": [
          "/js/url-swap.js"
        ],
        "share": true
      }
    },
    {
      "scope": {
        "path": "/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "amelioration-continue/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          },
          {
            "link": "/amelioration-continue.html",
            "title": "Amélioration continue"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "amelioration-continue/mesure/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          },
          {
            "link": "/amelioration-continue.html",
            "title": "Amélioration continue"
          },
          {
            "link": "/amelioration-continue/mesure.html",
            "title": "Suivi et mesure du succès"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "communaute/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          },
          {
            "link": "/communaute/accueil.html",
            "title": "Communauté"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "sondage"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Analyses, sondage et commentaires",
            "link": "https://www.canada.ca/fr/analytique.html"
          },
          {
            "title": "Sondage sur la réussite des tâches",
            "link": "/sondage/index.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "architecture"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          },
          {
            "title": "Spécifications de l'architecture de l'information",
            "link": "/architecture/specifications-contenu-architecture-information-canada.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "configurations-conception-communes/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          },
          {
            "title": "Modèles et configurations",
            "link": "/bibliotheque-modeles.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "crise/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          },
          {
            "link": "/crise/contenu.html",
            "title": "Aide-mémoire pour la conception du contenu des communications de crise"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "directives/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": "/"
          },
          {
            "link": "/directives/",
            "title": "Directives"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "directives/ia/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html",
            "title": "À propos de Canada.ca"
          },
          {
            "link": "/",
            "title": "Conception"
          },
          {
            "link": "/directives/index.html",
            "title": "Lignes directrices"
          },
          {
            "link": "/directives/ia/index.html",
            "title": "Applications d’aide alimentées par l’IA"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "mise-en-page/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "link": "/bibliotheque-modeles.html",
            "title": "Modèles et configurations"
          },
          {
            "link": "/modeles-recommandes/generique.html#discussion",
            "title": "Mise en page de base"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "modeles-obligatoire/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "link": "/bibliotheque-modeles.html",
            "title": "Modèles et configurations"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "modeles-recommandes/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "link": "/bibliotheque-modeles.html",
            "title": "Modèles et configurations"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "styles/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "link": "/bibliotheque-modeles.html",
            "title": "Modèles et configurations"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "retroaction/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Analyses, sondage et commentaires",
            "link": "https://www.canada.ca/fr/analytique.html"
          },
          {
            "title": "Outil de rétroaction",
            "link": "/retroaction/index.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "configurations-conception-communes/en-tete-global/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "link": "/bibliotheque-modeles.html",
            "title": "Modèles et configurations"
          },
          {
            "title": "En-tête général",
            "link": "/configurations-conception-communes/en-tete-general.html"
          }
        ],
        "permalink": "/configurations-conception-communes/:basename:output_ext"
      }
    },
    {
      "scope": {
        "path": "configurations-conception-communes/pied-page-general/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "title": "Modèles et configurations",
            "link": "/bibliotheque-modeles.html"
          },
          {
            "title": "Pied de page général",
            "link": "/configurations-conception-communes/pied-page.html"
          }
        ],
        "permalink": "/configurations-conception-communes/:basename:output_ext"
      }
    },
    {
      "scope": {
        "path": "index.md"
      },
      "values": {
        "breadcrumbs": [{
          "title": "À propos de Canada.ca",
          "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
        }]
      }
    },
    {
      "scope": {
        "path": "bibliotheque-modeles.md"
      },
      "values": {
        "breadcrumbs": [{
          "title": "À propos de Canada.ca",
          "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
        }, {
          "title": "Conception",
          "link": /
        }]
      }
    },
    {
      "scope": {
        "path": "guide-redaction/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "title": "Guide de rédaction du contenu du site Canada.ca",
            "link": "/guide-redaction/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "guide-redaction/index.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          }
        ]
      }
    },
    {
      "scope": {
        "path": "trouvez-modeles-configurations-conception-contenu-web.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Conception",
            "link": /
          },
          {
            "title": "Modèles et configurations",
            "link": "/bibliotheque-modeles.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "resumes-recherche/*.md"
      },
      "values": {
        "section-title": "Résumé de recherche",
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },{
            "title": "Conception",
            "link": /
          },
          {
            "title": "Résumés de recherche",
            "link": "/resumes-recherche/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "resumes-recherche/index.md"
      },
      "values": {
        "section-title": "",
        "breadcrumbs": [{
          "title": "À propos de Canada.ca",
          "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
        },{
            "title": "Conception",
            "link": /
          },]
      }
    }, {
      "scope": {
        "path": "a-propos"
      },
      "values": {
        "breadcrumbs": [{
          "title": "À propos de Canada.ca",
          "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
        }, {
          "title": "Conception",
          "link": /
        }]
      }
    },
    {
      "scope": {
        "path": "a-propos/index.md"
      },
      "values": {
        "breadcrumbs": true
      }
    },
    {
      "scope": {
        "path": "partenaires/*.md"
      },
      "values": {
        "section-title": "Travailler avec des partenaires",
        "breadcrumbs": [{
            "title": "À propos de Canada.ca",
            "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
          },
          {
            "title": "Travailler avec des partenaires",
            "link": "/partenaires/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "partenaires/index.md"
      },
      "values": {
        "section-title": "",
        "breadcrumbs": [{
          "title": "À propos de Canada.ca",
          "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
        }]
      }
    },
    {
      "scope": {
        "path": "a-propos/bureau-transformation-numerique.md"
      },
      "values": {
        "breadcrumbs": [{
          "title": "À propos de Canada.ca",
          "link": "https://www.canada.ca/fr/gouvernement/a-propos-canada-ca.html"
        }]
      }
    }
  ]
}
