analytics:
  providers:
  - adobe
  adobe:
    tracking_id: be5dfd287373/0127575cd23a/launch-f7c3e6060667
    service: TBS-DTO_BTN-SCT
baseurl: ""
global:
  contextualFooter:
    title:
      fr: Bureau de la transformation numérique (BTN)
    links:
      fr:
        - url: "/contactez-nous/"
          text: Contactez-nous
  lang: fr
plugins:
  - jekyll-remote-theme
remote_theme: wet-boew/gcweb-jekyll
title: Système de conception de Canada.ca
url: "https://conception.canada.ca"

# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      css:
        - /css/split-h1.css
        - https://use.fontawesome.com/releases/v5.15.4/css/all.css
      pageclass: cnt-wdth-lmtd
  - scope:
      path: "sondage"
    values:
      breadcrumbs:
      - title: À propos de Canada.ca
        link: https://www.canada.ca/fr/gouvernement/a-propos.html
      - title: Analyses, sondage et commentaires
        link: https://www.canada.ca/fr/analytique.html
      - title: Sondage sur la réussite des tâches
        link: sondage/index.html
      layout: default
  - scope:
      path: "architecture"
    values:
      breadcrumbs:
      - title: À propos de Canada.ca
        link: https://www.canada.ca/fr/gouvernement/a-propos.html
      - title: Système de conception de Canada.ca
        link: https://www.canada.ca/fr/gouvernement/a-propos/systeme-conception.html
      - title: Spécifications de l'architecture de l'information
        link: https://conception.canada.ca/architecture/specifications-contenu-architecture-information-canada.html
